[package]
name = "shambler"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.3"
rayon = "1.5.1"

#shalrath = { path = "../shalrath" }
shalrath = "0.2.5"

#usage = { path = "../../../usage", features = ["rayon"] }
usage = {version = "1.1.0", features = ["rayon"]}
